### ISSUE TITLE
Looking forward to k-Means Transformer code release

### ISSUE THREAD

**Issue by vadimkantorov** [google-research/deeplab2#109]
https://arxiv.org/abs/2207.04044 suggests that this is the good repo

**Comment by aquariusjay** [comment]
Hi @vadimkantorov,

Yes, we are preparing the open-source (no later than the end of this Tuesday).
Please stay tuned for one or two days.
Thanks for your patience.

Cheers,

**Comment by vadimkantorov** [comment]
I also found that Slot Attention is probably relevant to this work, but it's not cited / discussed...

**Comment by aquariusjay** [comment]
Hi @vadimkantorov,

FYI, kMaX-DeepLab is live now.
Closing the comment.

Cheers,

**Comment by one-award** [comment]
Hi @aquariusjay,
Thank you for sharing the great works.

I'm begginer at tensorflow and try to use the model for inference.
I downloaded released ckpt in [COCO Panoptic segmentation models](https://github.com/google-research/deeplab2/blob/main/g3doc/projects/kmax_deeplab.md) but there is no saved_model.pbtxt or sabed_model.pb
how to load pretrained weight?

**Comment by aquariusjay** [comment]
Hi @one-award,

Thanks for reporting the issue.
We currently do not provide any exported model for kMaX-DeepLab.
You should be able to generate one by yourself via the provided [export_model.py](https://github.com/google-research/deeplab2/blob/main/export_model.py).
On our end, we will update the [DeepLab_demo](https://github.com/google-research/deeplab2/blob/main/DeepLab_Demo.ipynb) soon, which will provide the saved_model.

Cheers,
