### ISSUE TITLE
Question for K-Max deeplab

### ISSUE THREAD

**Issue by lxtGH** [google-research/deeplab2#115]
@yucornetto Hi! Very impressive and nice work for k-Max Deeplab. I have two questions for comparison with k-Max Deeplab and Max Deeplab. 
1. From the configs, I saw the augmentation is different. It seems that k-Max Deeplab use stronger augmentation larger crop size [link](https://github.com/google-research/deeplab2/blob/916b7c8d1cda5c6528db21e38d6092d083f9a850/configs/coco/kmax_deeplab/kmax_meta_convnext_small_os32.textproto#L100)  and copy paste for thing/stuff mask [link](https://github.com/google-research/deeplab2/blob/916b7c8d1cda5c6528db21e38d6092d083f9a850/configs/coco/kmax_deeplab/kmax_meta_convnext_small_os32.textproto#L107). I wonder the effect of these augmentations for the final performance.  
2. For aux loss, what is effect after removing these aux loss  (beside PQ style loss) for k-Max Deeplab.

Best regards!
Thank you !!!!

**Comment by yucornetto** [comment]
Hi,

Thanks for your interest in our work.

1. The stronger augmentation aims to give an improved baseline over MaX-DeepLab and better align to other methods based on PyTorch + GPU. E.g., we use crop size 1281, which equals resizing longer edges to 1281 and padding shorter edges to 1281 during inference (TF+TPU requires a square and static input shape). This is similar to other methods (PyTorch + GPU) where the longer size is resized no longer than 1333. The larger crop size and copy-paste leads to a 47.5 COCO PQ for a R50 baseline w/ cross-attention (see Table 3 in Appendix of our paper). We use them in all of our experiments but did not ablate them for kMaX-DeepLab specifically.

2. The loss design mainly follows MaX-DeepLab, and we have not tried to remove them. You may refer to MaX-DeepLab's paper for their effects on MaX-DeepLab.

Please let me know if you have any more questions :)
