### ISSUE TITLE
[deeplab2 install] Error when compiling custom ops 

### ISSUE THREAD

**Issue by daebakk** [google-research/deeplab2#116]
When I run the following commands,  I got this error

TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
OP_NAME='deeplab2/tensorflow_ops/kernels/merge_semantic_and_instance_maps_op'

unilt now , no error

error command

GPU version

```
nvcc -std=c++14 -c -o ${OP_NAME}_kernel.cu.o ${OP_NAME}_kernel.cu.cc  > ${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC --expt-relaxed-constexpr
```

/home/kimdaehyun/anaconda3/envs/KmeansFormer/lib/python3.8/site-packages/tensorflow/include/tensorflow/core/platform/file_system.h(574): warning: overloaded virtual function "tensorflow::FileSystem::FilesExist" is only partially overridden in class "tensorflow::WrappedFileSystem"

/home/kimdaehyun/anaconda3/envs/KmeansFormer/lib/python3.8/site-packages/tensorflow/include/tensorflow/core/platform/file_system.h(574): warning: overloaded virtual function "tensorflow::FileSystem::CreateDir" is only partially overridden in class "tensorflow::WrappedFileSystem"

/home/kimdaehyun/anaconda3/envs/KmeansFormer/lib/python3.8/site-packages/tensorflow/include/tensorflow/core/platform/env.h(495): warning: overloaded virtual function "tensorflow::Env::RegisterFileSystem" is only partially overridden in class "tensorflow::EnvWrapper"

/home/kimdaehyun/anaconda3/envs/KmeansFormer/lib/python3.8/site-packages/tensorflow/include/tensorflow/core/platform/file_system.h(574): warning: overloaded virtual function "tensorflow::FileSystem::FilesExist" is only partially overridden in class "tensorflow::WrappedFileSystem"

/home/kimdaehyun/anaconda3/envs/KmeansFormer/lib/python3.8/site-packages/tensorflow/include/tensorflow/core/platform/file_system.h(574): warning: overloaded virtual function "tensorflow::FileSystem::CreateDir" is only partially overridden in class "tensorflow::WrappedFileSystem"

/home/kimdaehyun/anaconda3/envs/KmeansFormer/lib/python3.8/site-packages/tensorflow/include/tensorflow/core/platform/env.h(495): warning: overloaded virtual function "tensorflow::Env::RegisterFileSystem" is only partially overridden in class "tensorflow::EnvWrapper"

(KmeansFormer) kimdaehyun@kimdaehyun-System-Product-Name:~/Model_implementation/Panoptic_Segmentation/KmeansFormer$  warning: overloaded virtual function "tensorflow::FileSystem::FilesExist" is only partially overridden in class "tensorflow::WrappedFileSystem" warning: overloaded virtual function "tensorflow::FileSystem::FilesExist" is only partially overridden in class "tensorflow::WrappedFileSystem"

OS: Ubuntu 20.04.4 LTS
tensorflow and keras version : both 2.6.0
CUDA version  : 11.2
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

LD_LIBRARY_PATH=":/usr/local/cuda-11.2/lib64:/usr/local/cuda-11.2/extras/CUPTI/lib64"

gcc verson  : 7.5.0
gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I followed the installation guide on this page: https://github.com/google-research/deeplab2/blob/main/g3doc/setup/installation.md

What should I do ?

Thank you :)

**Comment by markweberdev** [comment]
Hi @daebakk,

I am using the same cuda version and nvcc compiler with TF 2.6. I also get the same warnings, but I don't get any error. Moreover, I don't see any error message in your description, could you elaborate on that?

Please also check if the compilation was successful by looking at the tensorflow_ops/kernel folder.

Best,
Mark

**Comment by daebakk** [comment]
> 

HI @markweberdev 
I'm a little late to answer, sorry

After trying again, the compilation worked successfully. 

When I first tried to run the following code, I got some error messages but now it's ok
```
python deeplab2/tensorflow_ops/python/kernel_tests/merge_semantic_and_instance_maps_op_test.py
```
Thank you for your advice.
