### ISSUE TITLE
How to debug in deeplab2

### ISSUE THREAD

**Issue by daebakk** [google-research/deeplab2#117]
Hello, 

I tried to debug 'Kmax Deeplab' but I cannot go into the call function in `[deeplab2/model/kmax_deeplab.py](https://github.com/google-research/deeplab2/blob/main/model/kmax_deeplab.py)` when I set the breakpoint as follows, and then the debugger just passes through the whole forward process.

![스크린샷, 2022-07-27 17-52-35](https://user-images.githubusercontent.com/41338783/181206136-b6274eb7-ae7a-426d-98e2-46f5d01c076f.png)

so I tried to debug and finally got to the code that seemed to execute the forward function
the code is in `quick_execute'`function in `my_path/tensorflow/python/eager/execute.py` as follows

![스크린샷, 2022-07-27 18-29-31](https://user-images.githubusercontent.com/41338783/181213762-958a8640-5109-4147-8ac4-a15c43735738.png)

after I run this code,
`tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name`

I checked that the forward process was already finished

before I go into this function, I checked executing_eagerly == True lik this

`executing_eagerly = ctx.executing_eagerly()` in `/home/kimdaehyun/.cache/JetBrains/PyCharm2021.3/remote_sources/-1311538014/-1764294251/tensorflow/python/eager/function.py`

I use Pycharm IDE and I set the debugging environment like this.

![스크린샷, 2022-07-27 17-58-11](https://user-images.githubusercontent.com/41338783/181206896-f02b8236-8928-4683-ae82-0b8b9e73b58e.png)

what should I do? 

Thank you :)

**Comment by markweberdev** [comment]
Hi @daebakk,

we're not supporting this way of debugging by default. Our trainer does not run in eager mode. We're using orbit for the training logic (see trainer.py). That again uses orbit which uses tf.functions by default. You could try to play around with the following, but we don't provide support here: https://www.tensorflow.org/api_docs/python/orbit/StandardTrainerOptions

Feel free to share your experience.

Best,
Mark

**Comment by daebakk** [comment]
> Hi @daebakk,
> 
> we're not supporting this way of debugging by default. Our trainer does not run in eager mode. We're using orbit for the training logic (see trainer.py). That again uses orbit which uses tf.functions by default. You could try to play around with the following, but we don't provide support here: https://www.tensorflow.org/api_docs/python/orbit/StandardTrainerOptions
> 
> Feel free to share your experience.
> 
> Best, Mark

Hi, @markweberdev 

Thank you for your advice.

Then, How can I debug deeplab2 model?

Could you give some examples?

**Comment by markweberdev** [comment]
I'd recommend starting with some tf.print for example. "debugging" in graph mode is a common issue, you'll find infos when googling/stackoverflow. It's not as convenient as you are used to.

**Comment by daebakk** [comment]
> I'd recommend starting with some tf.print for example. "debugging" in graph mode is a common issue, you'll find infos when googling/stackoverflow. It's not as convenient as you are used to.

I understood! 

Thank you :)
