### ISSUE TITLE
Do you have results of k-means Mask Transformer on ADE20K dataset?

### ISSUE THREAD

**Issue by MengzhangLI** [google-research/deeplab2#121]
Hi, first congrats to ECCV'2022 acceptance of k-means Mask Transformer.

I think it is an excellent work but I did not find results of ADE20K dataset which is widely used as benchmark in semantic segmentation task.

Could you share the performance of k-means Mask Transformer on ADE20K dataset if you implemented it?

Best,

**Comment by yucornetto** [comment]
Hi, thanks for the interest in our work.

We have not tried kMaX-DeepLab on ADE20K yet, perhaps we will try it in the near future, please stay tuned!

**Comment by yucornetto** [comment]
Hi,

We have just updated [kMaX-DeepLab's model zoo](https://github.com/google-research/deeplab2/blob/main/g3doc/projects/kmax_deeplab.md) with ADE20K results, welcome to check it!

**Comment by MengzhangLI** [comment]
> Hi,
> 
> We have just updated [kMaX-DeepLab's model zoo](https://github.com/google-research/deeplab2/blob/main/g3doc/projects/kmax_deeplab.md) with ADE20K results, welcome to check it!

Copy that. Thank you so much.
