### ISSUE TITLE
MobileNet config files missing for kMaX-DeepLab

### ISSUE THREAD

**Issue by rcruzgar** [google-research/deeplab2#123]
Hi!

I would like to use the MobileNet checkpoints from Simple training strategy section located here:

https://github.com/google-research/deeplab2/blob/main/g3doc/projects/imagenet_pretrained_checkpoints.md

but I can't find a corresponding configuration file here (I only see ResNet and ConvNeXt config files):

https://github.com/google-research/deeplab2/tree/main/configs/coco/kmax_deeplab

May I use the config file *kmax_meta_r50_os32.textproto* wit the MobileNet checkpoint? If I use ResNet-50 do I have to use this configuration file?

Best regards,
Rubén.

**Comment by yucornetto** [comment]
Hi,

Thanks for your interests. We have not tried kMaX with MobileNet backbones, but you may try it by modifying the kmax_meta_r50_os32.textproto and replace the backbone section with MobileNet.

Best,

**Comment by rcruzgar** [comment]
Thank you. I will try.
