### ISSUE TITLE
evaluator_options/num_vis_samples in textproto file is not taken into account

### ISSUE THREAD

**Issue by agaitanis** [google-research/deeplab2#127]
I set num_vis_samples: 20 in textproto file but I still get 10 images in the results/vis folder.

**Comment by aquariusjay** [comment]
Hi @agaitanis,

It shouldn't be the case.
Please make sure your setting (e.g., config) is correct.
Also, you could take a detailed look at the code (e.g., this [line](https://github.com/google-research/deeplab2/blob/916b7c8d1cda5c6528db21e38d6092d083f9a850/trainer/evaluator.py#L357)), which may help you debug.

Cheers,

**Comment by agaitanis** [comment]
This is my config options:

evaluator_options {
  continuous_eval_timeout: -1
  save_predictions: true
  save_raw_predictions: false
  num_vis_samples : 20
  detailed_ap_metrics : True
}

Are you sure? Did you check it? Does it work?

**Comment by agaitanis** [comment]
I removed the space before the colon in the line
num_vis_samples : 20
and it works.
