### ISSUE TITLE
Please provide a way to change the evaluation frequency

### ISSUE THREAD

**Issue by agaitanis** [google-research/deeplab2#128]
The evaluation frequency is set to 5000 steps and I can't find a way to change it.

**Comment by aquariusjay** [comment]
Hi @agaitanis,

Please check the proto (e.g., this [one](https://github.com/google-research/deeplab2/blob/main/evaluator.proto#L26))

Cheers,

**Comment by agaitanis** [comment]
This worked:
evaluator_options {
  eval_interval: 2000
}
Thanks
