### ISSUE TITLE
TypeError during deeplab2/compile.sh gpu

### ISSUE THREAD

**Issue by titq2022** [google-research/deeplab2#138]
The following error occurred while running `deeplab2/compile.sh gpu`.
Could you please tell me how to solve it?
![image](https://user-images.githubusercontent.com/115346408/194700620-59d1961a-dec6-4603-aa55-05381ffca3b9.png)

**Comment by aquariusjay** [comment]
I guess the error is similar to this [stackoverflow question](https://stackoverflow.com/questions/66154004/example-code-from-typing-library-causes-typeerror-type-object-is-not-subscrip).
Could you please try:
1. Upgrade your python >= 3.9
2. or, try change Line 204 in moat_blocks.py as follows:
from typing import List
def build(self, input_shape: List[int]) -> None:

**Comment by titq2022** [comment]
Thanks for the reply aquariusjay.

I tried number 2.
After some similar edits, it worked.

**Comment by aquariusjay** [comment]
Glad to know that it works.
Closing the issue.
