### ISSUE TITLE
error while testing the configuration! 

### ISSUE THREAD

**Issue by MustafaAlahmid** [google-research/deeplab2#140]
while testing the configuration i'm getting this error: 

> python deeplab2/trainer/evaluator_test.py
> Traceback (most recent call last):
>   File "deeplab2/trainer/evaluator_test.py", line 33, in <module>
>     from deeplab2.model import deeplab
>   File "/home/mus/Desktop/Seg/deeplab2/model/deeplab.py", line 27, in <module>
>     from deeplab2.model import builder
>   File "/home/mus/Desktop/Seg/deeplab2/model/builder.py", line 33, in <module>
>     from deeplab2.model.pixel_encoder import moat
>   File "/home/mus/Desktop/Seg/deeplab2/model/pixel_encoder/moat.py", line 32, in <module>
>     from deeplab2.model.layers.moat_blocks import MBConvBlock
>   File "/home/mus/Desktop/Seg/deeplab2/model/layers/moat_blocks.py", line 146, in <module>
>     class MBConvBlock(tf.keras.layers.Layer):
>   File "/home/mus/Desktop/Seg/deeplab2/model/layers/moat_blocks.py", line 204, in MBConvBlock
>     def build(self, input_shape: list[int]) -> None:
> TypeError: 'type' object is not subscriptable

I' m using ubunto 20.04
cuda 11.2
tensorflow 2.6.0
keras 2.6.0
gcc 8

**Comment by aquariusjay** [comment]
Hi @MustafaAlahmid,

Your issue is related to #138.
Please check the suggested solutions there.

Cheers,

**Comment by MustafaAlahmid** [comment]
> 

thanks, it worked
