### ISSUE TITLE
Implementations on the RaspberryPi and Google Coral Devboard

### ISSUE THREAD

**Issue by zain-altaf** [google-research/deeplab2#145]
Hi

I have a RaspberryPi 3 and Google Coral Mini Dev Board at the moment that I need to use to develop a project. I was wondering how the steps might differ for users who use this route of getting started with the repository? Is this repository open to just android and IOS or is it also applicable to the raspberrypi community as well?

Thanks!

**Comment by aquariusjay** [comment]
Hi @zain-altaf,

The repository is mainly used for pure research.
It does not support your use case.
Sorry about that.

Cheers,
