### ISSUE TITLE
Cannot compile protocol buffers

### ISSUE THREAD

**Issue by padmalcom** [google-research/deeplab2#18]
Hi, thanks for your framework. I followed the installation guide but got problems when compiling the protocol buffers. I followed the instructions exactly as you specified, except that I'm working on CentOS whereas you seem to work in Ubuntu.

(deeplab2) [user1@localhost deeplab2]$ pwd
/home/user1/deeplab2/deeplab2
(deeplab2) [user1@localhost deeplab2]$ cd ..
(deeplab2) [user1@localhost deeplab2]$ ls
cocoapi  deeplab2  init.sh  models
(deeplab2) [user1@localhost deeplab2]$ protoc deeplab2/*.proto --python_out=.
deeplab2/model.proto:178:3: Expected "required", "optional", or "repeated".
deeplab2/model.proto:178:27: Missing field number.
deeplab2/config.proto: Import "deeplab2/model.proto" was not found or had errors.
deeplab2/config.proto:31:12: "ModelOptions" is not defined.

Is it possible that I use the wrong protoc version?

(deeplab2) [user1@localhost deeplab2]$ protoc --version
libprotoc 2.5.0

**Comment by markweberdev** [comment]
Hi, 

The protoc version could be the issue. I am running 3.6.1. Please have a look [here](https://github.com/protocolbuffers/protobuf#protocol-compiler-installation) to find newer versions. If this solves the compilation error, please let us know so we can update the requirements regarding the protobuf compiler.

Best,
Mark

**Comment by padmalcom** [comment]
Hi Mark,
thank you, I just compiled protoc from github and could get rid of the error messages.

(deeplab2) [user1@localhost protobuf]$ /usr/local/bin/protoc --version
libprotoc 3.17.3
(deeplab2) [user1@localhost deeplab2]$ /usr/local/bin/protoc deeplab2/*.proto --python_out=.
(deeplab2) [user1@localhost deeplab2]$
