### ISSUE TITLE
Conda compatibility issues and how to fix

### ISSUE THREAD

**Issue by padmalcom** [google-research/deeplab2#22]
Hi, I tried to setup deeplab2 with anaconda (I recognized your note that there are dependency issues but it felt like a challenge :) ). 

The only issue I found is the following:
**ModuleNotFoundError: No module named 'pycocotools._mask'** when running the all in one compile script.

Fix: execute **make** in _cocoapi/PythonAPI_

My environment is a python 3.8 env on conda 4.10.1

**Comment by luminate22** [comment]
How can I contribute?

**Comment by padmalcom** [comment]
It was meant to be an information. I'll close this one.
