### ISSUE TITLE
Error when compiling custom ops (GPU)

### ISSUE THREAD

**Issue by mi2celis** [google-research/deeplab2#30]
When compiling the custom ops GPU support I get the  error below from a tensorflow header file 

Followed instructions for setting compile and loader flags
TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
OP_NAME='deeplab2/tensorflow_ops/kernels/merge_semantic_and_instance_maps_op'

Compiling for CPU completed without error

Compiling for GPU
nvcc -std=c++14 -c -o ${OP_NAME}_kernel.cu.o   ${OP_NAME}_kernel.cu.cc     ${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC --expt-relaxed-constexpr

/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/platform/file_system.h(556): warning: overloaded virtual function "tensorflow::FileSystem::FilesExist" is only partially overridden in class "tensorflow::WrappedFileSystem"

...
snip
...

/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/include/absl/functional/function_ref.h:\100:29: **error: parameter packs not expanded with ‘...’:
   template <typename F, typename = EnableIfCompatible<const F&>>**
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                
/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/include/absl/functional/function_ref.h:\100:29: note:         ‘Args’
/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/include/absl/functional/function_ref.h:114:13: **error: parameter packs not expanded with ‘...’:
       typename F, typename = EnableIfCompatible<F\*>,**
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

tensorflow-gpu          2.5.0

Any suggestions?

**Comment by markweberdev** [comment]
Hi,

These issues might be related to your CUDA version. Tensorflow 2.5 officially only supports CUDA 11.2. Please give us an update on whether this problem still persists.

Best,
Mark

**Comment by mi2celis** [comment]
That was it. Even though I have cuda 11.2 installed, nvcc 10 was still in my /usr/bin
Removed all nvidia and cuda installs and reinstalled 11.2 .
Thanks!
