### ISSUE TITLE
Missing 'checkpoint' File in the ImageNet Checkpoint Provided for ResNet-50-Beta

### ISSUE THREAD

**Issue by free-bit** [google-research/deeplab2#33]
I downloaded ImageNet checkpoint for ResNet-50-Beta from [here](https://github.com/google-research/deeplab2/blob/main/g3doc/projects/imagenet_pretrained_checkpoints.md). After extraction, folder structure for this checkpoint looks like this:
- `resnet50_beta_imagenet1k_strong_training_strategy/`
  - `ckpt-350.data-00000-of-00001`
  - `ckpt-350.index`

I adjusted the `initial_checkpoint` variable in the `configs/coco/panoptic_deeplab/resnet50_beta_os32.textproto` file such that it points to the downloaded `resnet50_beta_imagenet1k_strong_training_strategy` folder. However, when I run the `train.py` script, I receive `TypeError: Expected binary or unicode string, got None.` while the checkpoint is being loaded with `tf.train.load_checkpoint` method (within `trainer/runner_utils.py: _load_tf_model_garden_vision_checkpoint`).

I inspected the problem in debug mode and realized that `tf.train.load_checkpoint` method internally requires a file named `checkpoint` under the specified `initial_checkpoint` path. I made a run without setting `initial_checkpoint` to generate an example file. Then, it revealed that a `checkpoint` file like the one below is required by the tensorflow loader to load checkpoints properly. The following file was missing in the provided checkpoint. So, I created it manually:

- `checkpoint`:
model_checkpoint_path: "ckpt-350"
all_model_checkpoint_paths: "ckpt-350"

And placed it under `resnet50_beta_imagenet1k_strong_training_strategy` folder, resulting in the following folder structure for `initial_checkpoint` path:
- `resnet50_beta_imagenet1k_strong_training_strategy/`
  - `checkpoint`
  - `ckpt-350.data-00000-of-00001`
  - `ckpt-350.index`

This additional file seems to solve the problem. Briefly, I think such a `checkpoint` file must be added wherever it is missing.

**Comment by yjlin0223** [comment]
ckpt-350.index， it get use.

**Comment by markweberdev** [comment]
Hi free-bit,

This is one way to do it, but there is a simpler way to do it. Just specify the path to the checkpoint, in your case `"/your_path/resnet50_beta_imagenet1k_strong_training_strategy/ckpt-350"`. I hope that helps and simplifies your experimental pipeline.

Best,
Mark
