### ISSUE TITLE
Problems about how to use optical flow in iou_tracker.py

### ISSUE THREAD

**Issue by Dash-coder** [google-research/deeplab2#39]
I want to employ the optional parameters: `optical_flow` while runing iou_tracker.py for evaluating STQ. But it involves two files with different suffixes: `_OCCLUSION_EXT = '.occ_forward'` and `_FLOW_EXT = '.flow_forward'`. I want to know the meaning the above two files and how to generate above two files through optical flow diagram.

**Comment by ClaireXie** [comment]
Hi Dash-coder,

Thanks for your interest. We ran our internal state-of-the-art optical flow method (e.g. RAFT: Recurrent All Pairs Field Transforms for Optical Flow) to get the per pixel optical forward flow and occlusion array, saved in numpy format:

```
with tf.io.gfile.GFile(filename, 'w') as outfile:
    np.save(outfile, array)
```

You can get the optical flow arrays similarly from public repo such as https://github.com/princeton-vl/RAFT.

**Comment by aquariusjay** [comment]
Closing the issue, as there is no active discussion for a while.
Please feel free to reopen or create a new one if you still have any questions.

**Comment by ysharma1126** [comment]
For the occlusion array, how was the forward-backward consistency check implemented? 
Was eq. (5) in [Sundaram et al., 2010](https://lmb.informatik.uni-freiburg.de/Publications/2010/Bro10e/sundaram_eccv10.pdf) used? If so, were the same hyperparameters used, or were they tuned, and if so, how?
