### ISSUE TITLE
About the performance on cityscapes panoptic segmentation of MaX-DeepLab

### ISSUE THREAD

**Issue by HarborYuan** [google-research/deeplab2#41]
Hi,

Thanks for your great work on creating this codebase. I am trying to use the MaX-DeepLab in my own project. I want to ask about what the results of MaX-DeepLab on the cityscapes panoptic segmentation val set would be like if you have tested before. I would really appreciate it if it is possible to report this even if it is just an unofficial approximate result.

Thanks.

**Comment by lxtGH** [comment]
The same question. What are the results of MaX-DeepLab on Cityscapes?

**Comment by csrhddlam** [comment]
Hi,

Thanks for raising this issue, but unfortunately no, we have not tested MaX-DeepLab on Cityscapes. We didn't get a chance to do more experiments on more datasets due to the paper submission deadline. We will possibly do more datasets and report our results later.

**Comment by aquariusjay** [comment]
Closing the issue as there is no active discussion for a while.
Please feel free to reopen or create a new one if you have any more questions.
