### ISSUE TITLE
Cannot be training?

### ISSUE THREAD

**Issue by pingjun18-li** [google-research/deeplab2#44]
thank you for the great codes!
and when i run training codes "python trainer/train.py    --config_file='configs/coco/max_deeplab/max_deeplab_s_os16_res641_100k.textproto'     --mode='train'     --model_dir='checkpoint/max_deeplab_s_os16_res641_100k'     --num_gpus=1"
there error logs:

I0814 02:46:35.469203 139737541474112 train.py:65] Reading the config file.
I0814 02:46:35.472224 139737541474112 train.py:69] Starting the experiment.
2021-08-14 02:46:35.472912: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-14 02:46:36.288440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30987 MB memory:  -> device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:88:00.0, compute capability: 7.0
I0814 02:46:36.301358 139737541474112 train_lib.py:105] Using strategy <class 'tensorflow.python.distribute.one_device_strategy.OneDeviceStrategy'> with 1 replicas
I0814 02:46:36.621985 139737541474112 deeplab.py:57] Synchronized Batchnorm is used.
I0814 02:46:36.622916 139737541474112 axial_resnet_instances.py:144] Axial-ResNet final config: {'num_blocks': [3, 4, 6, 3], 'backbone_layer_multiplier': 1.0, 'width_multiplier': 1.0, 'stem_width_multiplier': 1.0, 'output_stride': 16, 'classification_mode': False, 'backbone_type': 'resnet_beta', 'use_axial_beyond_stride': 16, 'backbone_use_transformer_beyond_stride': 32, 'extra_decoder_use_transformer_beyond_stride': 32, 'backbone_decoder_num_stacks': 0, 'backbone_decoder_blocks_per_stage': 1, 'extra_decoder_num_stacks': 0, 'extra_decoder_blocks_per_stage': 1, 'max_num_mask_slots': 128, 'num_mask_slots': 128, 'memory_channels': 256, 'base_transformer_expansion': 1.0, 'global_feed_forward_network_channels': 256, 'high_resolution_output_stride': 4, 'activation': 'relu', 'block_group_config': {'attention_bottleneck_expansion': 2, 'drop_path_keep_prob': 0.800000011920929, 'drop_path_beyond_stride': 16, 'drop_path_schedule': 'linear', 'positional_encoding_type': None, 'use_global_beyond_stride': 0, 'use_sac_beyond_stride': -1, 'use_squeeze_and_excite': False, 'conv_use_recompute_grad': False, 'axial_use_recompute_grad': True, 'recompute_within_stride': 0, 'transformer_use_recompute_grad': False, 'axial_layer_config': {'query_shape': (129, 129), 'key_expansion': 1, 'value_expansion': 2, 'memory_flange': (32, 32), 'double_global_attention': False, 'num_heads': 8, 'use_query_rpe_similarity': True, 'use_key_rpe_similarity': True, 'use_content_similarity': True, 'retrieve_value_rpe': True, 'retrieve_value_content': True, 'initialization_std_for_query_key_rpe': 1.0, 'initialization_std_for_value_rpe': 1.0, 'self_attention_activation': 'softmax'}, 'dual_path_transformer_layer_config': {'num_heads': 8, 'bottleneck_expansion': 2, 'key_expansion': 1, 'value_expansion': 2, 'feed_forward_network_channels': 2048, 'use_memory_self_attention': True, 'use_pixel2memory_feedback_attention': True, 'transformer_activation': 'softmax'}}, 'bn_layer': functools.partial(<class 'keras.layers.normalization.batch_normalization.SyncBatchNormalization'>, momentum=0.9900000095367432, epsilon=0.0010000000474974513), 'conv_kernel_weight_decay': 0.0}
I0814 02:46:36.977007 139737541474112 deeplab.py:96] Setting pooling size to (41, 41)
I0814 02:46:36.977362 139737541474112 aspp.py:135] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
WARNING:tensorflow:AutoGraph could not transform <function resize_to_range at 0x7f16dcac2a70> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: [Errno 28] No space left on device: '/tmp/tmp3onbzwhs.py'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
W0814 02:46:40.066303 139737541474112 ag_logging.py:146] AutoGraph could not transform <function resize_to_range at 0x7f16dcac2a70> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: [Errno 28] No space left on device: '/tmp/tmp3onbzwhs.py'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function get_random_scale at 0x7f16dcac25f0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: [Errno 28] No space left on device: '/tmp/tmpfij6_rpa.py'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
W0814 02:46:40.161577 139737541474112 ag_logging.py:146] AutoGraph could not transform <function get_random_scale at 0x7f16dcac25f0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: [Errno 28] No space left on device: '/tmp/tmpfij6_rpa.py'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function randomly_scale_image_and_label at 0x7f16dcac2680> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: [Errno 28] No space left on device: '/tmp/tmpjt5b9l39.py'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
W0814 02:46:40.261782 139737541474112 ag_logging.py:146] AutoGraph could not transform <function randomly_scale_image_and_label at 0x7f16dcac2680> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: [Errno 28] No space left on device: '/tmp/tmpjt5b9l39.py'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Traceback (most recent call last):
  File "trainer/train.py", line 76, in <module>
    app.run(main)
  File "/data/anaconda3/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/data/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "trainer/train.py", line 72, in main
    FLAGS.num_gpus)
  File "/data/PanopticFCN-main/deeplab2/trainer/train_lib.py", line 137, in run_experiment
    trainer = trainer_lib.Trainer(config, deeplab_model, losses, global_step)
  File "/data/PanopticFCN-main/deeplab2/trainer/trainer.py", line 137, in __init__
    only_semantic_annotations=not support_panoptic)
  File "/data/PanopticFCN-main/deeplab2/trainer/runner_utils.py", line 130, in create_dataset
    return reader(dataset_config.batch_size)
  File "/data/PanopticFCN-main/deeplab2/data/dataloader/input_reader.py", line 89, in __call__
    self._generator_fn, num_parallel_calls=tf.data.experimental.AUTOTUNE)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1868, in map
    preserve_cardinality=True)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 5024, in __init__
    use_legacy_function=use_legacy_function)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4218, in __init__
    self._function = fn_factory()
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3151, in get_concrete_function
    *args, **kwargs)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3116, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4195, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4125, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/data/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: in user code:

    /data/PanopticFCN-main/deeplab2/data/sample_generator.py:159 __call__  *
        return self.call(**sample_dict)
    /data/PanopticFCN-main/deeplab2/data/sample_generator.py:215 call  *
        resized_image, image, label, prev_image, prev_label, depth = (
    /data/PanopticFCN-main/deeplab2/data/preprocessing/input_preprocessing.py:266 preprocess_image_and_label  *
        processed_image, label = preprocess_utils.randomly_scale_image_and_label(
    /data/PanopticFCN-main/deeplab2/data/preprocessing/preprocess_utils.py:267 randomly_scale_image_and_label  **
        if scale == 1.0:
    /data/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:900 __bool__
        self._disallow_bool_casting()
    /data/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:507 _disallow_bool_casting
        self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
    /data/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:496 _disallow_in_graph_mode
        " this function with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

I'd appreciate it if anyone could tell me how to solve it.

**Comment by markweberdev** [comment]
Hi pingjun18-li,

Please excuse my late response. Could you provide me more information about the batch size you were using on the V100? The default config has a batch size of 64 which will not fit on a single GPU. Please let me know all changes that you have done to the max_deeplab_s_os16_res641_100k.textproto config before I look more into it.

Thanks
Mark

**Comment by aquariusjay** [comment]
Closing the issue since there is no active discussion for a while.
Please feel free to re-open it if you have any question.
