### ISSUE TITLE
How to use the PNG format in my own dataset?

### ISSUE THREAD

**Issue by ilaripih** [google-research/deeplab2#48]
On the "Convert your own dataset" page it says that the values in the panoptic map should use this format:
`panoptic_label = semantic_label * label_divisor + instance_id`

I assume this applies to both the "raw" and "png" format? If so, do I need to create single channel 32-bit PNG images, and how do I do that?

Of course it's straightforward to use the "raw" format but that results in massive TFRecord dataset size.

**Comment by ClaireXie** [comment]
Hi ilaripih,

You can refer to how we created the panoptic map for KITTI-STEP dataset: https://github.com/google-research/deeplab2/blob/e038967579b9c9f8acf55edae5c20988bb6eb0cd/data/utils/create_step_panoptic_maps.py#L106

Here we encode the panoptic map with the following PNG format: 
```
R: semantic
G: instance // 256
B: instance % 256
```
 And we decode the png here: https://github.com/google-research/deeplab2/blob/e038967579b9c9f8acf55edae5c20988bb6eb0cd/data/build_step_data.py#L181-L186

**Comment by ilaripih** [comment]
Thanks for the quick response. To me it looks like the `encode_panoptic_map` code you're referring to is meant for creating intermediate PNG files before creating the final TFRecord dataset which uses the "raw" (int32) format. I'm creating the TFRecord dataset directly from my own dataset, skipping the intermediate steps.

I successfully encoded the panoptic labels in PNG format in "image/segmentation/class/encoded" and set the "image/segmentation/class/format" field to "png" but it looks like the Deeplab2 code still wants to use the raw format and is complaining about the PNG data:

```
Traceback (most recent call last):
  File "deeplab2/trainer/train.py", line 76, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "deeplab2/trainer/train.py", line 72, in main
    FLAGS.num_gpus)
  File "/workspace/deeplab2/trainer/train_lib.py", line 191, in run_experiment
    steps=config.trainer_options.solver_options.training_number_of_steps)
  File "/workspace/models/orbit/controller.py", line 240, in train
    self._train_n_steps(num_steps)
  File "/workspace/models/orbit/controller.py", line 439, in _train_n_steps
    train_output = self.trainer.train(num_steps_tensor)
  File "/workspace/models/orbit/standard_runner.py", line 146, in train
    self._train_loop_fn(self._train_iter, num_steps)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 3040, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1964, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Input to DecodeRaw has length 18802 that is not a multiple of 4, the size of int32
	 [[{{node DecodeRaw}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[while/body/_1/IteratorGetNext]]
	 [[while/body/_1/DeepLabFamilyLoss/MaXDeepLabLoss/maximum_bipartite_matching/while/body/_8657/DeepLabFamilyLoss/MaXDeepLabLoss/maximum_bipartite_matching/while/find_augmenting_path/while/body/_8938/DeepLabFamilyLoss/MaXDeepLabLoss/maximum_bipartite_matching/while/find_augmenting_path/while/mul/_724]]
  (1) Invalid argument:  Input to DecodeRaw has length 18802 that is not a multiple of 4, the size of int32
	 [[{{node DecodeRaw}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[while/body/_1/IteratorGetNext]]
```

I think I'm hitting this line that forces the use of the "raw" format in panoptic datasets: https://github.com/google-research/deeplab2/blob/main/data/data_utils.py#L353
I'll try the raw/int32 format.

**Comment by ilaripih** [comment]
With the "raw" format I can run the training code.

**Comment by ClaireXie** [comment]
Yes, current we only support "raw" format creating tfrecord dataset. 
You might need to either try with raw format or modify the `_decode_label` in data_utils to decode png data.

**Comment by ilaripih** [comment]
Thanks. I can manage with the raw format, it's working.

**Comment by Shaiken** [comment]
> Yes, current we only support "raw" format creating tfrecord dataset.
> You might need to either try with raw format or modify the `_decode_label` in data_utils to decode png data.

may i ask you how transfer raw, i got same question.
