### ISSUE TITLE
DeepLabv3+ weights

### ISSUE THREAD

**Issue by sjdh** [google-research/deeplab2#67]
In the example notebooks there are lists with checkpoints, but those lists do not include DeepLabv3+. 
Do you have weights for DeepLabv3+ with MobilenetV3 publicly available? 
If so, can you give me the URL?

Thank you

**Comment by aquariusjay** [comment]
Hi @sjdh,

Thanks for the issue.
We currently do not have any DeepLabv3+ w/ MobilenetV3 weights for this open-source library.
You could refer to our previous [library](https://github.com/tensorflow/models/tree/master/research/deeplab).

Cheers,
