### ISSUE TITLE
 whitout config_pd2

### ISSUE THREAD

**Issue by Aoldcat1997** [google-research/deeplab2#68]
Hi 
   i download the source code, but i don't find the config_pd2 file.

**Comment by ClaireXie** [comment]
Hi Aoldcat1997,

config_pd2 is automatically generated by compiling *.proto file as instructed in https://github.com/google-research/deeplab2/blob/main/g3doc/setup/installation.md#compile-protocol-buffers.

**Comment by Aoldcat1997** [comment]
thanks i have solve this,
