### ISSUE TITLE
Missing config files

### ISSUE THREAD

**Issue by felsi89** [google-research/deeplab2#69]
https://github.com/google-research/deeplab2/blob/main/g3doc/projects/panoptic_deeplab.md
the links for the config files of MobilenetV3-S and MobilenetV3-L are dead

https://github.com/google-research/deeplab2/tree/main/configs/cityscapes/panoptic_deeplab
and the provided config files with output stride 32 don't match

**Comment by yuanliangzhe** [comment]
Hi, We just pushed the MobileNet configs and the links should be working now. Sorry for the inconvenience.

**Comment by felsi89** [comment]
Thank you! :)
I tried one and training from imagenet1k ckpts works.
