### ISSUE TITLE
Question about bounding boxes in labels for MaxDeepLab

### ISSUE THREAD

**Issue by EnnioEvo** [google-research/deeplab2#71]
Thank you for this amazing work,

I have a doubt regarding MaxDeepLab: as far as I have understood there is no need in the labels for the bounding boxes ground truth, is it correct?
For example in the Coco dataset, the format for the panoptic labels expects, in every segment of each image, a field bbox (`annotations[n].segments_info[m].bbox`). So, if I want to train MaxDeepLab on the Coco dataset, it makes no difference if I set every bbox field to [0,0,0,0], right?

**Comment by aquariusjay** [comment]
Hi @EnnioEvo,

We do not use any bounding box annotation.
If you are interested in the details, you could check [build_coco_data.py ](https://github.com/google-research/deeplab2/blob/main/data/build_coco_data.py)to see how we converts COCO dataset for training MaX-DeepLab.

Cheers,
