### ISSUE TITLE
Panoptic-DeepLab: unable to load pretrained checkpoints

### ISSUE THREAD

**Issue by songlin** [google-research/deeplab2#73]
Hi,

I am trying to evaluate a pre-trained checkpoint file given [here](https://github.com/google-research/deeplab2/blob/main/g3doc/projects/panoptic_deeplab.md). But the checkpoint file cannot be loaded:
```
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file 
/media/xxx/ExtremeSSD/resnet50_os32_panoptic_deeplab_cityscapes_trainfine.tar.gz: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
```
The configuration in `config/cityscapes/panoptic_deeplab/resnet50_os32_merge_with_pure_tf_func.textproto` is as follows:
```
experiment_name: "panoptic-cs"
model_options {
  # Update the path to the initial checkpoint (e.g., ImageNet
  # pretrained checkpoint).
  initial_checkpoint: "/media/xxx/ExtremeSSD/resnet50_os32_panoptic_deeplab_cityscapes_trainfine.tar.gz"
...
```

The checkpoint tar file is downloaded using the link in the guide `panoptic_deeplab.md`. 

Thank you for the help

**Comment by markweberdev** [comment]
Hi,

Could you please extract the checkpoint from the archive and then let the initial_checkpoint point to that file?

For example: "/media/xxx/ExtremeSSD/resnet50_os32_panoptic_deeplab_cityscapes_trainfine/ckpt-60000"

Hope that helps.
