### ISSUE TITLE
VIP-DeepLab results

### ISSUE THREAD

**Issue by p-andra** [google-research/deeplab2#78]
Hello @joe-siyuan-qiao,

Thank you for your work! Can you please post what results are expected to get with VIP-DeepLab on SemKITTI-DVPS with ResNet-50-beta starting from Imagenet and Cityscapes pretrained weights?

I am currently trying to train and evaluate the network on SemKITTI-DVPS, however I have some issues and I am trying to figure out what is the problem.

**Comment by lxtGH** [comment]
Me too

**Comment by lxtGH** [comment]
@joe-siyuan-qiao  @joe-siyuan-qiao  @joe-siyuan-qiao  @joe-siyuan-qiao   @joe-siyuan-qiao

**Comment by HarborYuan** [comment]
@joe-siyuan-qiao

**Comment by lxtGH** [comment]
> Hello @joe-siyuan-qiao,
> 
> Thank you for your work! Can you please post what results are expected to get with VIP-DeepLab on SemKITTI-DVPS with ResNet-50-beta starting from Imagenet and Cityscapes pretrained weights?
> 
> I am currently trying to train and evaluate the network on SemKITTI-DVPS, however I have some issues and I am trying to figure out what is the problem.
I tried many times. It can not rerproduce the results.

**Comment by joe-siyuan-qiao** [comment]
Thanks for your interest. We are currently working on preparing model zoo. Please stay tuned. Thanks

**Comment by joe-siyuan-qiao** [comment]
The model zoo for ViP-DeepLab is updated [here](https://github.com/google-research/deeplab2/blob/main/g3doc/projects/vip_deeplab.md). Thanks for your patience! Closing this issue.
