### ISSUE TITLE
how to do semantic segmentation on video using saved model from tensorflow-2?

### ISSUE THREAD

**Issue by PritiDrishtic** [google-research/deeplab2#80]
Currently we have TF2 on production environment so wanted to do semantic segmentation on video using saved_model.pb (downloaded model with saved_model.pb)
Video segmentation worked for frozen graph using TF-1 but TF-2 dont support frozen graph so please provide script or any working example which will work on saved_model.pb.

**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
TensorFlow version (use command below): **2.5**
Python version: **3.6**
GCC/Compiler version (if compiling from source): **7.5**
CUDA/cuDNN version: **11.2**
GPU model and memory: **T4 GPU**

**Comment by aquariusjay** [comment]
Hi @PritiDrishtic,

Thank you for reporting the issue.
Unfortunately, your issue is more related to TensorFlow support.
Please report the issue to the TensorFlow team.
Closing the issue, since it is not related to our library.

Cheers,
