### ISSUE TITLE
How to segment specific objects on pre-trained model and store annotations?

### ISSUE THREAD

**Issue by varungupta31** [google-research/deeplab2#85]
I'm running the provided the Google Colab notebook, and I am able to get desired segmentations.
However, I'm only interested in segmenting the 'pole' and 'traffic sign' classes from the cityscapes dataset, and ignore other classes, and finally wish to obtain the annotation of the segmentation, so that I can mask those objects for some other application.

Is there a quick way to do so?

Thank you.

**Comment by aquariusjay** [comment]
Hi @varungupta31,

I think you can simply convert the final predicted segmentation results, by converting those classes that you do not need to background class (or any class label you like).

Cheers,

**Comment by varungupta31** [comment]
thanks for the reply.
I tried modifying the colab notebook. I changed:

```
def _cityscapes_label_colormap():
  """Creates a label colormap used in CITYSCAPES segmentation benchmark.

  See more about CITYSCAPES dataset at https://www.cityscapes-dataset.com/
  M. Cordts, et al. "The Cityscapes Dataset for Semantic Urban Scene Understanding." CVPR. 2016.

  Returns:
    A 2-D numpy array with each row being mapped RGB color (in uint8 range).
  """
  colormap = np.zeros((256, 3), dtype=np.uint8)
  colormap[0] = [128, 64, 128]
  colormap[1] = [244, 35, 232]
  colormap[2] = [70, 70, 70]
  colormap[3] = [102, 102, 156]
  colormap[4] = [190, 153, 153]
  colormap[5] = [153, 153, 153]
  colormap[6] = [250, 170, 30]
  colormap[7] = [220, 220, 0]
  colormap[8] = [107, 142, 35]
  colormap[9] = [152, 251, 152]
  colormap[10] = [70, 130, 180]
  colormap[11] = [220, 20, 60]
  colormap[12] = [255, 0, 0]
  colormap[13] = [0, 0, 142]
  colormap[14] = [0, 0, 70]
  colormap[15] = [0, 60, 100]
  colormap[16] = [0, 80, 100]
  colormap[17] = [0, 0, 230]
  colormap[18] = [119, 11, 32]
  return colormap


def _cityscapes_class_names():
  return ('road', 'sidewalk', 'building', 'wall', 'fence', 'pole',
          'traffic light', 'traffic sign', 'vegetation', 'terrain', 'sky',
          'person', 'rider', 'car', 'truck', 'bus', 'train', 'motorcycle',
          'bicycle')


def cityscapes_dataset_information():
  return DatasetInfo(
      num_classes=19,
      label_divisor=1000,
      thing_list=tuple(range(11, 19)),
      colormap=_cityscapes_label_colormap(),
      class_names=_cityscapes_class_names())
```
to

```
def _cityscapes_label_colormap():
  """Creates a label colormap used in CITYSCAPES segmentation benchmark.

  See more about CITYSCAPES dataset at https://www.cityscapes-dataset.com/
  M. Cordts, et al. "The Cityscapes Dataset for Semantic Urban Scene Understanding." CVPR. 2016.

  Returns:
    A 2-D numpy array with each row being mapped RGB color (in uint8 range).
  """
  colormap = np.zeros((256, 3), dtype=np.uint8)
  colormap[0] = [128, 64, 128]
  colormap[1] = [244, 35, 232]
  colormap[2] = [70, 70, 70]
  return colormap


def _cityscapes_class_names():
  return ( 'pole', 'traffic sign', 'road')


def cityscapes_dataset_information():
  return DatasetInfo(
      num_classes=3,
      label_divisor=1000,
      thing_list=tuple(range(11, 19)),
      colormap=_cityscapes_label_colormap(),
      class_names=_cityscapes_class_names())
```
but now my results are messed up.
With the original code, I got the result -

![download](https://user-images.githubusercontent.com/51288316/157607776-5e5e398e-8826-43b3-9ef5-e95f528f3e99.png)


but after the edit, I get - 

![download](https://user-images.githubusercontent.com/51288316/157607702-46d6ba57-0516-442d-b03c-285bbb9bfa28.png)

What am I missing?
Thank you.
@aquariusjay

**Comment by YknZhu** [comment]
I believe putting semantic_id to ignore list would be a good step. In addition, you can reset colors of these unused classes to 0. E.g. in your use case, you only need color map for class 0 (road), 5 (pole) and 7(traffic sign). The corresponding colormap would be:

```
  colormap = np.zeros((256, 3), dtype=np.uint8)
  colormap[0] = [128, 64, 128]
  colormap[5] = [153, 153, 153]
  colormap[7] = [220, 220, 0]
```

**Comment by varungupta31** [comment]
> I believe putting semantic_id to ignore list would be a good step.

I tried this, only difference it makes is that the labels for classes other than 0,5 and 7 are being marked 'ignore' but still being displayed/segmented with a colormap.

>  you can reset colors of these unused classes to 0.

can you please elaborate? 
colormap[n] expects 3 values, simply doing colormap[1] = [0] or 0 will cause an error, and doing colormap[1] = [0,0,0] will change the mask color to black. I want that these classes are not being segmented (with any color).

When I tried changing the classes from 18 to 3 (removing the labels, changing number of classes parameter, and  removed the corresponding colormaps), I got erraneous segmentations as shown in the 2nd image above.

Thank for your reply.

**Comment by aquariusjay** [comment]
For those pixels that will be remapped to `ignore' should have instance label remapped to 0 as well. Otherwise, they will be visualized with some similar colors, as what you have now.

**Comment by aquariusjay** [comment]
Closing the issue, as there is not active discussion for a long time.
Please feel free to reopen it if there is still any problem.
