### ISSUE TITLE
Help Setting up conda environment with CUDA<11

### ISSUE THREAD

**Issue by varungupta31** [google-research/deeplab2#86]
I'm following the instructions mentioned [here](https://github.com/google-research/deeplab2/blob/main/g3doc/setup/installation.md), and creating a conda environment to run this project. 

I installed python 3.5.4 and tensorflow 2.0.0 (cuda 10.0).
Since I don't have sudo access on the server, I did `pip install protobuf-compiler` and was able to run the `protoc` command.
But I ran into some compatibility issues witht the library `GRPCIO`. Tensorflow<2.5 requires a specific grpcio version not compatible with the protobuf-compiler being installed. (am I isntalling the protobuf-compiler the right way? I wan't very confident on compiling the packages from source, hence I tried this)

I can use CUDA 10.0, 10.1, 10.2.

If anyone else was successful setting up this project on a CUDA<11 system, kindly share the conda `.yaml` file or the packages with the specific version, that didn't give any version clashes.

TIA

**Comment by aquariusjay** [comment]
Hi @varungupta31,

Sorry to hear your issue.
Unfortunately, it may be hard for us to help resolve it, since it is not related to the code/model.
I am closing the issue, and maybe you could ask for help at some other forums (e.g, [stackoverflow](https://stackoverflow.com/)).

Cheers,
