### ISSUE TITLE
custom dataset size

### ISSUE THREAD

**Issue by amroghoneim** [google-research/deeplab2#88]
Hello.

I am currently in the process of finetuning with a custom dataset. I was wondering if you can advice on a specific minimum dataset size that can allow me to have good results given that I split the data for training testing and validation.

Thank you

**Comment by aquariusjay** [comment]
Hi @amroghoneim,

We do not have any standard for fine-tuning on small datasets, which is more like an experimental thing.
The rule of thumb instead would be trying to prepare the dataset as large as possible.

Cheers,
