### ISSUE TITLE
missing config_pb2

### ISSUE THREAD

**Issue by zhixiongzh** [google-research/deeplab2#90]
Hi,

in the `train.py`, you use `from deeplab2 import config_pb2`, but there is not such definition of `config_pb2`, so that I can not import this `config_pb2`.
Do you remove this file?

Thanks for any help.

**Comment by AndreiBaraian** [comment]
@zhixiongzh Remember to execute export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/models:`pwd`/cocoapi/PythonAPI from below deeplab2. config_pb2.py can be found in deeplab2/config_pb2.py

**Comment by zhixiongzh** [comment]
> @zhixiongzh Remember to execute export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/models:`pwd`/cocoapi/PythonAPI from below deeplab2. config_pb2.py can be found in deeplab2/config_pb2.py

I do export that and I can `import deeplab2`, the problem is like, there is not such file `config_pb2.py` everywhere in this repository.
After running `find . -name "config_pb.py"`. I got no result.

**Comment by zhixiongzh** [comment]
ah, I found out only after running `${PATH_TO_PROTOC} deeplab2/*.proto --python_out=.` then I can get `config_pb.py`.
