### ISSUE TITLE
If i just want a semantic segmentation

### ISSUE THREAD

**Issue by Shaiken** [google-research/deeplab2#93]
sorry, this confused me about just want semantic segmentation
seems deeplab2 can not work when custom dataset only semantic ...

**Comment by aquariusjay** [comment]
Hi @Shaiken,

You may be able to modify this semantic-segmentation-only [config](https://github.com/google-research/deeplab2/blob/main/configs/cityscapes/panoptic_deeplab/resnet50_os32_semseg.textproto) for your use case.
For the groundtruth, panoptic label is a general representation that includes both semantic and instance labels.

Cheers,

**Comment by Shaiken** [comment]
really appreciate, i will try it
